var config = require('./../../config');

module.exports = {
	"nameError": "Name can not be empty", 
	"passwordEmptyError": "Password can not be empty",
	"PasswordError": "Invalid password.",
	"missingParamError": "Please check the parameters passed",
	"emailValidationError": "Please enter a valid email addesss",
	"ServerError":"Server error occurred, Please try again",
	"NotYourMoveError":"Not your move",
	"invalidRequestParams": "Invalid Request parameters passed",
	"AccountError":"Account not found, Please try again",
	"invalidCredentials":"Please check your credentials & try again",
	"mobileValidationError":"Please enter a valid mobile number",
	"usernameValidationError":"Please enter a valid username",
	"passwordValidationError":"Password must be at least 8 characters",
	"passwordLengthValidationError":"Please enter a valid password",
	"emailExistError":"An account already exist with same email address",
	"mobileExistError":"An account already exist with same mobile number",
	"otpGenerateError":"Error sending otp, please check your mobile number",
	"registerSuccess":"SUCCESS",
	"loginSuccess":"SUCCESS",
	"accountDeactivated":"Your account has been deactivated by admin",
	"accountDeleted":"Your account has been deleted by admin",
	"verificationPending":"Please Verify your mobile number to continue",
	"otpValidationError":"Invalid otp entered",
	"otpExpired":"Otp has been expired, Please generate again",
	"deviceTypeError":"Invalid device type provided. Allowed ['ios','android','web']",
	"tokenExpired":"Unauthorised! Access denied",
	"autologinSuccess":"SUCCESS",
	"OtpSent":"Otp sent successfully",
	"mobileAccountDoesNotExistError":"No account found on our system associated with this mobile number",
	"emailAccountDoesNotExistError":"No account found on our system associated with this email address",
	"resetPasswordSuccess":"SUCCESS",
	"resetPasswordEmailSent":"SUCCESS",
	"resetPasswordEmailError":"Error sending reset password email, please try again",
	"listSecurityQuesSuccess":"SUCCESS",
	"setSecurityQuesSuccess":"SUCCESS",
	"incorrectPassword":"Incorrect password entered",
	"changePasswordSuccess":"Password changed successfully",
	"success":"SUCCESS",
	"TransactionsHistory":"SUCCESS",
	"invalidPlanId":"Invalid plan id provided",
	"invalidOldPassError":"Invalid Old Password",
	"invalidNewPassError":"Invalid New Password",
	"invalidConfirmPassError":"Invalid Confirm Password",
	"invalidIdError": "Invaild id provided",
	"invalidAmountError": "Invalid amount entered",
	"noApplicationFound": "No job application found for given details",
	"invalidResponseError": "Invalid response provided",
	"fileUploadError": "Error uploading file",
	"userActivate": "User Activated Successfully",
    "userDeActivate": "User De-Activated Successfully",
	"missingParamErrorAdmin":"Please complete all fields to continue",
	"missingParamErrorAdminR":"Please complete all the required fields to continue",
	"resetMessageSent": "Reset link sent via message successfully",
	"notAuthorised": "You are not authorised to perform this action",
	"otpSendError": "Error occurred while sending otp",
	"oldPasswordMatchError":"Incorrect password entered for old password",
	"accountExistError": "Account does not exist",
	"roleExist": "Role already exist",
	"roleAssignedError": "Can not remove role, as its assigned to a data executive",
	"recordNoAccessError": "Can not delete this role, its permanent!",
	"recordNoAccessUpdateError": "Can not update this role, its permanent!",
	"invalidReferralCodeError": "Invalid Referral Code Provided",
	"newFbAccountError": "Please provide fb user details",
	"profileUpdateError": "Profile updated successfully!",
	"pushSuccess":"Push SUCCESS",
	"pushError":"Push Error",
	"referralSuccess":"Referral Record!",
	"pushValidationError": "Please provide valid Boolean value.",
	"emailVerificationSuccess": "Your email address has been verified.",
	"emailVerificationSuccessMsg": "Now you can enjoy all features of Ludo Fantasy. Thank you!",
	"passwordNotMatchError" : "Password does not match!",
	"webPassSuccess": "Password change successfully!",
	"uniqueUserNameError": "This username has been taken. Please choose another.",
	"usernameValidationError": "Username must be at least 3 characters long and less than 12 characters.",
	"tableSuccess": "Private Room Created Successfully.",
	"insufficientBalanceError": "Sorry, you have insufficient balance to play this game.",
	"insufficientWithdrawlError": "Sorry, you have insufficient balance to place this request.",
	"alreadyPlaying": "Already Playing On Another Table.",
	"tableDoesNotExist": "Table Does Not Exist",
	"tableAlreadyFullErr": "Table is already full.",
	"invalidEmail": "Invalid email address entered",
	"referralPushSuccess": "Congratulations! You received referral bonus",
	"withdrawlPushSuccess": "Congratulations! Your withdrawl request processed successfully.",
	"withdrawlPushReject": "Sorry! Your withdrawl request is rejected.",
	"requestSuccess": "Request processed successfully",
	"accountVerifiedError": "Your email id is not verified!",
	"minWithdrawalLimit": "Minimum withdrawal limit is 50",
	"invalidRquest": "Invalid request id provided",
	"withdrawalRequestProcessed": "Request processed successfully",
	"addmoneyRequestProcessed": "Request processed successfully",
	"adminAmountPushSuccess": "Your account has been credited",
	"gamePushSuccess": "Congratulations! You have won a game.",
	"bootAmountLessError": "Boot amount can not be less than 10",
	"bootAmountExist": "This boot amount is already exist",
	"invalidCommission": "Invaild value entered",
	"passwordNotMatch": "New password and confirm password does not match",
};